# Generated by Django 6.0 on 2025-12-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Bài viết', 'verbose_name_plural': 'Bài viết'},
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Tự động tạo từ nội dung nếu để trống', verbose_name='Tóm tắt'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp'), ('published', 'Đã xuất bản')], db_index=True, default='draft', max_length=10),
        ),
    ]
