# Generated by Django 6.0 on 2025-12-23 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Nguyen Van A', max_length=255, verbose_name='Họ và tên')),
                ('headline', models.CharField(help_text='Vd: Fullstack Developer & Security Researcher', max_length=255, verbose_name='Chức danh')),
                ('bio', models.TextField(blank=True, verbose_name='Giới thiệu ngắn (Bio)')),
                ('avatar', models.ImageField(upload_to='personal/avatar/', verbose_name='Ảnh đại diện')),
                ('cv_pdf', models.FileField(blank=True, help_text='File PDF để user tải về', upload_to='personal/cv/', verbose_name='File CV (PDF)')),
                ('email', models.EmailField(max_length=254, verbose_name='Email liên hệ public')),
                ('location', models.CharField(help_text='Vd: Ho Chi Minh City, Vietnam', max_length=255, verbose_name='Địa điểm')),
                ('is_open_to_work', models.BooleanField(default=True, verbose_name='Đang tìm việc?')),
                ('available_for_freelance', models.BooleanField(default=True, verbose_name='Nhận Freelance?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hồ sơ cá nhân (Profile)',
                'verbose_name_plural': 'Hồ sơ cá nhân',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'X (Twitter)'), ('facebook', 'Facebook'), ('website', 'Personal Website'), ('other', 'Khác')], default='other', max_length=20)),
                ('url', models.URLField(verbose_name='Link Profile')),
                ('display_text', models.CharField(blank=True, help_text='Vd: @nguyenvana', max_length=50, verbose_name='Tên hiển thị')),
                ('icon_class', models.CharField(blank=True, help_text='Class icon (vd: ri-github-fill) nếu dùng RemixIcon', max_length=50, verbose_name='Icon Class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='personal.userprofile')),
            ],
            options={
                'verbose_name': 'Mạng xã hội',
                'verbose_name_plural': 'Mạng xã hội',
                'ordering': ['order'],
            },
        ),
    ]
