# Generated by Django 6.0 on 2025-12-23 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_email',
            field=models.EmailField(blank=True, help_text='Email hiển thị trên web. Để trống nếu muốn ẩn.', max_length=254, verbose_name='Email công việc (Public)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Class icon (vd: ri-github-fill hoặc fa-brands fa-github)', max_length=50, verbose_name='Icon Class'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'X (Twitter)'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('website', 'Website cá nhân'), ('other', 'Khác')], default='other', max_length=20, verbose_name='Nền tảng'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(verbose_name='Đường dẫn (URL)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='personal/avatars/', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cv_pdf',
            field=models.FileField(blank=True, help_text='File PDF để user tải về', null=True, upload_to='personal/cvs/', verbose_name='File CV (PDF)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='Nguyen Van A', max_length=255, verbose_name='Họ và tên hiển thị'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='headline',
            field=models.CharField(help_text='Vd: Senior Fullstack Developer', max_length=255, verbose_name='Chức danh'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Vd: Ho Chi Minh City, Vietnam', max_length=255, verbose_name='Địa điểm'),
        ),
    ]
