# Generated by Django 6.0 on 2025-12-23 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255, verbose_name='Trường học')),
                ('degree', models.CharField(help_text='Vd: Bachelor of Science in Computer Science', max_length=255, verbose_name='Bằng cấp')),
                ('field_of_study', models.CharField(blank=True, max_length=255, verbose_name='Chuyên ngành')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc (dự kiến)')),
                ('grade', models.CharField(blank=True, max_length=100, verbose_name='Điểm số / Xếp loại')),
                ('description', models.TextField(blank=True, help_text='Thành tích, hoạt động ngoại khóa...', verbose_name='Mô tả thêm')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='resume/schools/', verbose_name='Logo trường')),
            ],
            options={
                'verbose_name': 'Học vấn',
                'verbose_name_plural': 'Học vấn',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên nhóm')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Nhóm kỹ năng',
                'verbose_name_plural': 'Nhóm kỹ năng',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Tên công ty')),
                ('role', models.CharField(max_length=255, verbose_name='Vị trí / Chức danh')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, help_text='Để trống nếu hiện tại đang làm', null=True, verbose_name='Ngày kết thúc')),
                ('is_current', models.BooleanField(default=False, verbose_name='Đang làm việc tại đây')),
                ('description', models.TextField(help_text='Hỗ trợ Markdown hoặc gạch đầu dòng', verbose_name='Mô tả công việc')),
                ('technologies_used', models.CharField(blank=True, help_text='Vd: Python, Django, React (ngăn cách bằng dấu phẩy)', max_length=500, verbose_name='Công nghệ sử dụng')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='resume/companies/', verbose_name='Logo công ty')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
            ],
            options={
                'verbose_name': 'Kinh nghiệm làm việc',
                'verbose_name_plural': 'Kinh nghiệm làm việc',
                'ordering': ['-is_current', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vd: Python, Rust, Docker', max_length=100, verbose_name='Tên kỹ năng')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='resume/skills/', verbose_name='Icon/Logo')),
                ('proficiency', models.PositiveIntegerField(default=0, help_text='Từ 0 đến 100', verbose_name='Độ thành thạo (%)')),
                ('is_featured', models.BooleanField(default=False, help_text='Hiển thị ở trang chủ hoặc phần tóm tắt', verbose_name='Nổi bật')),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.skillcategory')),
            ],
            options={
                'verbose_name': 'Kỹ năng (Skill)',
                'verbose_name_plural': 'Kỹ năng (Skill)',
                'ordering': ['category__order', 'order'],
            },
        ),
    ]
