// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/resume": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/projects" | "/blog" | "/blog/:slug" | "/resume" | "/contact";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/projects" | "/blog" | "/blog/:slug" | "/resume" | "/contact";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects";
  };
  "routes/blog.tsx": {
    id: "routes/blog";
    page: "/blog";
  };
  "routes/post.tsx": {
    id: "routes/post";
    page: "/blog/:slug";
  };
  "routes/resume.tsx": {
    id: "routes/resume";
    page: "/resume";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layout": typeof import("./app/routes/layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/projects": typeof import("./app/routes/projects.tsx");
  "routes/blog": typeof import("./app/routes/blog.tsx");
  "routes/post": typeof import("./app/routes/post.tsx");
  "routes/resume": typeof import("./app/routes/resume.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
};