# Generated by Django 6.0 on 2025-12-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Portfolio', max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('seo_keywords', models.CharField(blank=True, max_length=500)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='core/seo/', verbose_name='Ảnh Share Link (OG)')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Bảo trì')),
            ],
            options={
                'verbose_name': 'Cấu hình Website',
                'verbose_name_plural': 'Cấu hình Website',
            },
        ),
    ]
