# Generated by Django 6.0 on 2025-12-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Cấu hình hệ thống', 'verbose_name_plural': 'Cấu hình hệ thống'},
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='seo_keywords',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='core/assets/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_text',
            field=models.CharField(blank=True, default='© 2024 Built with Django & Remix.', max_length=255, verbose_name='Footer Text'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='core/assets/', verbose_name='Logo Website'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_description',
            field=models.TextField(blank=True, verbose_name='Mô tả SEO mặc định'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='site_keywords',
            field=models.CharField(blank=True, help_text='Ngăn cách bằng dấu phẩy', max_length=500, verbose_name='Keywords SEO'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='Nếu bật, Frontend sẽ hiển thị trang bảo trì.', verbose_name='Chế độ bảo trì'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='core/assets/', verbose_name='Ảnh chia sẻ MXH (OG Image)'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='site_name',
            field=models.CharField(default='My Portfolio', max_length=255, verbose_name='Tên Website'),
        ),
    ]
