# Generated by Django 6.0 on 2025-12-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên người gửi'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='user_agent',
            field=models.CharField(blank=True, default=1, max_length=255, verbose_name='Trình duyệt'),
            preserve_default=False,
        ),
    ]
