# Generated by Django 6.0 on 2025-12-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='blue', help_text='Màu hiển thị trên badge (blue, green, red...)', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên dự án')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(help_text='Hiện ở Card bên ngoài', max_length=500, verbose_name='Mô tả ngắn')),
                ('full_description', models.TextField(blank=True, help_text='Hỗ trợ Markdown', verbose_name='Mô tả chi tiết')),
                ('thumbnail', models.ImageField(upload_to='projects/thumbnails/', verbose_name='Ảnh thumbnail')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/covers/', verbose_name='Ảnh bìa chi tiết')),
                ('demo_url', models.URLField(blank=True, verbose_name='Live Demo')),
                ('repo_url', models.URLField(blank=True, verbose_name='GitHub Repo')),
                ('is_featured', models.BooleanField(default=False, help_text='Ghim lên trang chủ', verbose_name='Nổi bật')),
                ('is_public', models.BooleanField(default=True, verbose_name='Công khai')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='projects', to='projects.projecttag')),
            ],
            options={
                'verbose_name': 'Dự án (Product)',
                'verbose_name_plural': 'Dự án (Product)',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
