# Generated by Django 6.0 on 2025-12-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Ghim lên trang chủ', verbose_name='Nổi bật'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Công khai'),
        ),
    ]
